[package]
name = "temportal-engine"
version = "0.1.0"
authors = ["Dustin Yost <dustin.yost.t@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
temportal-math = { path = "../temportal-math" }
sdl2 = "0.34"
ash = "0.32.1"
egui = "0.11.0"

[build-dependencies]
extern-reader = { path = "../extern-reader" }
