[package]
name = "temportal-engine"
version = "0.1.0"
authors = ["Dustin Yost <dustin.yost.t@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
temportal-math = { path = "../temportal-math" }
temportal-graphics = { path = "../temportal-graphics" }
egui = "0.11.0"
physx = "0.11.0"
structopt = "0.3"
raw-window-handle = "0.3.3"
shaderc = "0.7.2"

[dependencies.sdl2]
version = "0.34"
features = ["raw-window-handle"]

[build-dependencies]
extern-reader = { path = "../extern-reader" }
