[package]
name = "temportal-engine-editor"
version = "0.1.0"
authors = ["Dustin Yost <dustin.yost.t@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
temportal-engine = { path = "../engine" }
bytemuck = "1.7"
log = { version = "0.4", features = ["std"] }
rmp = "0.8"
rmp-serde = "0.15"
serde = { version = "1.0", features = ["derive"] }
winit = "0.25"
zip = "0.5"

copypasta = "0.7"
egui = "0.14"
serde_json = "1.0"
shaderc = "0.7"
freetype-rs = "0.28"
image = "0.23"
cargo_toml = "0.9"
semver = "1.0.3"
